# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

steps:
  - task: AzureCLI@2
    displayName: 'Create Storage Account'
    inputs:
      azureSubscription: '$(ado_service_connection_rg)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az storage account create -n $(terraform_st_storage_account) -g $(terraform_st_resource_group) -l $(location) --sku Standard_LRS'