# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# parameters:
# - name: jumphost_username
#   type: string
#   default: "azureuser"
# - name: jumphost_password
#   type: string
#   default: "ThisIsNotVerySecure!"

steps:
  - task: TerraformTaskV2@2
    displayName: 'Terraform apply'
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/$(terraform_workingdir)'
      commandOptions: '-var "location=$(location)" -var "prefix=$(namespace)" -var "postfix=$(postfix)" -var "environment=$(environment)" -var "enable_aml_computecluster=$(enable_aml_computecluster)" -var "enable_monitoring=$(enable_monitoring)" -var "client_secret=$(CLIENT_SECRET)"'
      environmentServiceNameAzureRM: '$(ado_service_connection_rg)'