# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

steps:
  - task: TerraformTaskV2@2
    displayName: 'Terraform plan'
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/$(terraform_workingdir)'
      commandOptions: '-var "location=$(location)" -var "prefix=$(namespace)" -var "postfix=$(postfix)" -var "environment=$(environment)" -var "enable_aml_computecluster=$(enable_aml_computecluster)"'
      environmentServiceNameAzureRM: '$(ado_service_connection_rg)'