name: allocate-traffic

on:
  workflow_call:
    inputs:
      endpoint_name:
        required: true
        type: string
      resource_group:
        required: true
        type: string
      workspace_name:
        required: true
        type: string
      traffic_allocation:
        required: true
        type: string
    secrets:
      creds:
        required: true
jobs:
  allocate-traffic:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          creds: ${{secrets.creds}}
          enable-AzPSSession: true
      - name: install-extension
        run: az extension add -n ml -y
      - name: update-extension
        run: az extension update -n ml
      - name: allocate-traffic
        run: |
          az ml online-endpoint update --name ${{ inputs.endpoint_name }} --traffic "${{ inputs.traffic_allocation }}" \
          --resource-group ${{ inputs.resource_group }} --workspace-name ${{ inputs.workspace_name }}
