name: create-endpoint

on:
  workflow_call:
    inputs:
      resource_group:
        required: true
        type: string
      workspace_name:
        required: true
        type: string
      endpoint_name:
        required: true
        type: string
      endpoint_type:
        required: true
        type: string
      endpoint_auth_mode:
        required: true
        type: string
    secrets:
      creds:
        required: true
jobs:
  create-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          # Azure login can use either Service Principal or OIDC authentication:
          # 1. Service Principal: Uses client ID, tenant ID, client secret/certificate
          #    Example: creds: ${{secrets.creds}}
          #
          # 2. OIDC (OpenID Connect): More secure, uses federated identity credentials
          #    Example:
          #    client-id: ${{ secrets.AZURE_CLIENT_ID }}
          #    tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          #    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          #    enable-oidc: true
          #
          # Choose the appropriate method based on your security requirements
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # Uncomment next line to use OIDC
          # enable-oidc: true
      - name: install-extension
        run: az extension add -n ml -y
      - name: update-extension
        run: az extension update -n ml
      - name: create-environment-from-file
        run: |
          az ml ${{ inputs.endpoint_type }}-endpoint create -n ${{ inputs.endpoint_name }} \
          --auth_mode ${{ inputs.endpoint_auth_mode }} --resource-group ${{ inputs.resource_group }} \
          --workspace-name ${{ inputs.workspace_name }}
