name: register-custom-model

on:
  workflow_call:
    inputs:
      resource_group:
        required: true
        type: string
      workspace_name:
        required: true
        type: string
      name:
        required: true
        type: string
      job-name:
        required: true
        type: string
      named-output:
        required: true
        type: string
    secrets:
      creds:
        required: true
jobs:
  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          creds: ${{secrets.creds}}
          enable-AzPSSession: true
      - name: install-extension
        run: az extension add -n ml -y
      - name: update-extension
        run: az extension update -n ml
      - name: create-model-from-job-output
        run: |
          az ml model create --path azureml://jobs/${{ inputs.job-name }}/outputs/${{ inputs.named-output }}/ --resource-group ${{ inputs.resource_group }} \
          --workspace-name ${{ inputs.workspace_name }} --name ${{ inputs.name }}